<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3startertemplate"
 *
 * Auto generated by Extension Builder 2015-06-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TYPO3 Starter Template',
	'description' => 'Based extension providing a set of configuration and template',
	'category' => 'templates',
	'author' => 'Marco Malagoli',
	'author_email' => 'malagolim@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.4.0-7.99.99',
			'realurl' => '',
			'typo3_console' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
